version: '3.8'

services:
  frontend:
    image: ghcr.io/skpokala/meal-planner-app-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Use the external host IP or domain name - update this with your actual server IP/domain
      - REACT_APP_API_URL=http://${HOST_IP:-localhost}:5000/api
    depends_on:
      - meal-planner-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meal-planner-network

  meal-planner-backend:
    image: ghcr.io/skpokala/meal-planner-app-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://meal-planner-mongo:27017/meal-planner
      - JWT_SECRET=${JWT_SECRET:-meal-planner-jwt-secret-change-this-in-production}
      - PORT=5000
      # Allow requests from the host IP and common localhost variants
      - FRONTEND_URL=http://${HOST_IP:-localhost}:3000,http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - meal-planner-mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meal-planner-network

  meal-planner-mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=meal-planner
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meal-planner-network

volumes:
  mongo_data:
    driver: local

networks:
  meal-planner-network:
    driver: bridge 