name: Build and Publish ML Service to GHCR (Deprecated)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ml

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "ML image is now built by .github/workflows/publish.yml. Use this workflow only for manual/one-off builds."


